### ISSUE TITLE
AttributeError: '_CalibratedClassifier' object has no attribute 'calibrators'

### ISSUE THREAD

**Issue by namz** [Darkempire78/Raid-Protect-Discord-Bot#11]
Hello,

Getting following warning when running the bot

```
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator TfidfTransformer from version 0.23.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator TfidfVectorizer from version 0.23.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator LinearSVC from version 0.23.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator LabelEncoder from version 0.23.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator _SigmoidCalibration from version 0.23.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator CalibratedClassifierCV from version 0.23.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
```

and then when a user tries  > ?verify

following error comes and bot crashes

```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/discord/client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "/root/Raid-Bot/Cogs/onMessage.py", line 93, in on_message
    profanity = predict(words) # profanity2 = predict_prob(words)
  File "/usr/local/lib/python3.7/dist-packages/profanity_check/profanity_check.py", line 12, in predict
    return model.predict(vectorizer.transform(texts))
  File "/usr/local/lib/python3.7/dist-packages/sklearn/calibration.py", line 385, in predict
    return self.classes_[np.argmax(self.predict_proba(X), axis=1)]
  File "/usr/local/lib/python3.7/dist-packages/sklearn/calibration.py", line 362, in predict_proba
    proba = calibrated_classifier.predict_proba(X)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/calibration.py", line 648, in predict_proba
    zip(pos_class_indices, predictions.T, self.calibrators):
AttributeError: '_CalibratedClassifier' object has no attribute 'calibrators'
```

**Comment by namz** [comment]
Any thoughts ? @Darkempire78

**Comment by Darkempire78** [comment]
There is not ?verify command in the bot

**Comment by Darkempire78** [comment]
I have no error when I write ``?verify``
Can you give me more data about your problem ?

**Comment by namz** [comment]
So i tried again and reinstalled all dependencies with pip3 for python3.  If install them just with pip i get following error 

`aiohttp requires Python '>=3.4.2' but the running Python is 2.7.17` and it stops. 

So after installing them with pip3, Captcha setup and assigning a role setup went fine. But as soon as a new user joined (1stly, he landed in verification channel which bot created) then bot crashed with following message this time.

```
We have logged in as Raid#1663
1.5.1
Ignoring exception in on_member_join
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/discord/client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "/root/Raid/Cogs/onJoin.py", line 70, in on_member_join
    font = ImageFont.truetype(font= "arial", size= 60)
  File "/root/.local/lib/python3.7/site-packages/PIL/ImageFont.py", line 648, in truetype
    return freetype(font)
  File "/root/.local/lib/python3.7/site-packages/PIL/ImageFont.py", line 645, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/root/.local/lib/python3.7/site-packages/PIL/ImageFont.py", line 194, in __init__
    font, size, index, encoding, layout_engine=layout_engine
OSError: cannot open resource
```
I am on Ubuntu 18, with python3.7.5 installed

**Comment by Darkempire78** [comment]
There are no issue.
Please download the last version of each module and use the new version of python. Python 2 is the former version, you can not use it. The bot can works only for the last version of python (~3.6+)

**Comment by namz** [comment]
As i mentioned above i did downloaded all latest packs as per requirements and I am on python 3.7.5

**Comment by namz** [comment]
`OSError: cannot open resource` message comes when all latest modules of requirements are downloaded

**Comment by Darkempire78** [comment]
All works well on my Windows.
Check this : https://stackoverflow.com/questions/47694421/pil-issue-oserror-cannot-open-resource
Tell me if you solve your issue

**Comment by namz** [comment]
Yes i have. I have tried few diff combos like "Arial" , "arial.ttf" , "arial.tff" , "unic" etc. Its same issue with them as well.

I also tried this on Ubuntu 20 with Python 3.8 . This time, as soon as i run bot i get warning messages as per original post (1st post here), user joins the server and sits in verification channel and nothing happens. If user types something in verification channel bot crashes with same error as 1st post i.e.` AttributeError: '_CalibratedClassifier' object has no attribute 'calibrators'`

**Comment by namz** [comment]
Thoughts ?

**Comment by Darkempire78** [comment]
I'm sorry but I can't fix an error that I can't reproduce.
The error certainly comes from your environment and your manipulations, I think that sites like stackoverflow are more apt to help you.

**Comment by namz** [comment]
Alright no worries. I have tried it on Windows 10, Ubuntu 18 and Ubuntu 20 now. Anyways thank you !

**Comment by Darkempire78** [comment]
Fixed with the last release!
