### ISSUE TITLE
Failed to load OnJoin And OnMessage 

### ISSUE THREAD

**Issue by R5B-MAX** [Darkempire78/Raid-Protect-Discord-Bot#13]
![image](https://user-images.githubusercontent.com/60330925/106394483-e1c3f380-640d-11eb-8f33-fb4b352f9f67.png)
so weird thats why when i anyone join they dont know what to do and leave

**Comment by Darkempire78** [comment]
Use the new version

**Comment by Darkempire78** [comment]
Works ? @R5B-MAX
