### ISSUE TITLE
errno 28

### ISSUE THREAD

**Issue by kittylegitcheck** [Darkempire78/Raid-Protect-Discord-Bot#14]
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ if [[ -d .git ]] && [[ ${AUTO_UPDATE} == "1" ]]; then git pull; fi; if [[ ! -z ${PY_PACKAGES} ]]; then pip install -U --target /home/container/ ${PY_PACKAGES}; fi; if [[ -f /home/container/requirements.txt ]]; then pip install -U --target /home/container/ -r requirements.txt; fi; /usr/local/bin/python /home/container/${BOT_PY_FILE}
Collecting aiohttp
  Downloading aiohttp-3.7.4-cp38-cp38-manylinux2014_x86_64.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 4.3 MB/s 
Collecting Augmentor
  Downloading Augmentor-0.2.8-py2.py3-none-any.whl (38 kB)
Collecting discord.py
  Downloading discord.py-1.6.0-py3-none-any.whl (779 kB)
     |████████████████████████████████| 779 kB 14.2 MB/s 
Collecting nudepy
  Downloading nudepy-0.5.1.tar.gz (35 kB)
Collecting numpy
  Downloading numpy-1.20.1-cp38-cp38-manylinux2010_x86_64.whl (15.4 MB)
     |████████████████████████████████| 15.4 MB 11.5 MB/s 
Collecting async-timeout<4.0,>=3.0
  Downloading async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
Collecting attrs>=17.3.0
  Downloading attrs-20.3.0-py2.py3-none-any.whl (49 kB)
     |████████████████████████████████| 49 kB 951 kB/s 
Collecting chardet<4.0,>=2.0
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 42.5 MB/s 
Collecting future>=0.16.0
  Downloading future-0.18.2.tar.gz (829 kB)
     |████████████████████████████████| 829 kB 34.9 MB/s 
Collecting multidict<7.0,>=4.5
  Downloading multidict-5.1.0-cp38-cp38-manylinux2014_x86_64.whl (159 kB)
     |████████████████████████████████| 159 kB 15.7 MB/s 
Collecting Pillow>=5.2.0
  Downloading Pillow-8.1.1-cp38-cp38-manylinux1_x86_64.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 21.5 MB/s 
Collecting tqdm>=4.9.0
  Downloading tqdm-4.58.0-py2.py3-none-any.whl (73 kB)
     |████████████████████████████████| 73 kB 412 kB/s 
Collecting typing-extensions>=3.6.5
  Downloading typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.6.3-cp38-cp38-manylinux2014_x86_64.whl (324 kB)
     |████████████████████████████████| 324 kB 7.3 MB/s 
Collecting idna>=2.0
  Downloading idna-3.1-py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 1.3 MB/s 
Building wheels for collected packages: nudepy, future
  Building wheel for nudepy (setup.py) ... done
  Created wheel for nudepy: filename=nudepy-0.5.1-cp38-cp38-linux_x86_64.whl size=31962 sha256=de40e2d8fc149232ee1805e54c97212262a40240c9ea9aaade43d795a31c8529
  Stored in directory: /home/container/.cache/pip/wheels/94/16/af/5ea7da07512d0f8fdf79004b31c53d06f1f44763ac3ecb42cb
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491058 sha256=048a9d25dd901ce3cbab616042b12b1b5e00a02c6f6e43c6d8c05ee5b96fdbf7
  Stored in directory: /home/container/.cache/pip/wheels/8e/70/28/3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4
Successfully built nudepy future
Installing collected packages: multidict, idna, yarl, typing-extensions, chardet, attrs, async-timeout, tqdm, Pillow, numpy, future, aiohttp, nudepy, discord.py, Augmentor
ERROR: Could not install packages due to an EnvironmentError: [Errno 28] No space left on device

WARNING: You are using pip version 20.3; however, version 21.0.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
Collecting git+https://github.com/dimitrismistriotis/profanity-check (from -r requirements.txt (line 6))
  Cloning https://github.com/dimitrismistriotis/profanity-check to /tmp/pip-req-build-xf0nn7co
Collecting aiohttp
  Using cached aiohttp-3.7.4-cp38-cp38-manylinux2014_x86_64.whl (1.5 MB)
ERROR: Could not install packages due to an EnvironmentError: [Errno 28] No space left on device

WARNING: You are using pip version 20.3; however, version 21.0.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/home/container/main.py", line 3, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'
container@pterodactyl~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ if [[ -d .git ]] && [[ ${AUTO_UPDATE} == "1" ]]; then git pull; fi; if [[ ! -z ${PY_PACKAGES} ]]; then pip install -U --target /home/container/ ${PY_PACKAGES}; fi; if [[ -f /home/container/requirements.txt ]]; then pip install -U --target /home/container/ -r requirements.txt; fi; /usr/local/bin/python /home/container/${BOT_PY_FILE}
Collecting aiohttp
  Using cached aiohttp-3.7.4-cp38-cp38-manylinux2014_x86_64.whl (1.5 MB)
Collecting Augmentor
  Using cached Augmentor-0.2.8-py2.py3-none-any.whl (38 kB)
Collecting discord.py
  Using cached discord.py-1.6.0-py3-none-any.whl (779 kB)
Collecting nudepy
  Using cached nudepy-0.5.1-cp38-cp38-linux_x86_64.whl
Collecting numpy
  Using cached numpy-1.20.1-cp38-cp38-manylinux2010_x86_64.whl (15.4 MB)
Collecting async-timeout<4.0,>=3.0
  Using cached async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
Collecting attrs>=17.3.0
  Using cached attrs-20.3.0-py2.py3-none-any.whl (49 kB)
Collecting chardet<4.0,>=2.0
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting future>=0.16.0
  Using cached future-0.18.2-py3-none-any.whl
Collecting multidict<7.0,>=4.5
  Using cached multidict-5.1.0-cp38-cp38-manylinux2014_x86_64.whl (159 kB)
Collecting Pillow>=5.2.0
  Using cached Pillow-8.1.1-cp38-cp38-manylinux1_x86_64.whl (2.2 MB)
Collecting tqdm>=4.9.0
  Using cached tqdm-4.58.0-py2.py3-none-any.whl (73 kB)
Collecting typing-extensions>=3.6.5
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting yarl<2.0,>=1.0
  Using cached yarl-1.6.3-cp38-cp38-manylinux2014_x86_64.whl (324 kB)
Collecting idna>=2.0
  Using cached idna-3.1-py3-none-any.whl (58 kB)
Installing collected packages: multidict, idna, yarl, typing-extensions, chardet, attrs, async-timeout, tqdm, Pillow, numpy, future, aiohttp, nudepy, discord.py, Augmentor
ERROR: Could not install packages due to an EnvironmentError: [Errno 28] No space left on device

WARNING: You are using pip version 20.3; however, version 21.0.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
Collecting git+https://github.com/dimitrismistriotis/profanity-check (from -r requirements.txt (line 6))
  Cloning https://github.com/dimitrismistriotis/profanity-check to /tmp/pip-req-build-zt38alcs
Collecting aiohttp
  Using cached aiohttp-3.7.4-cp38-cp38-manylinux2014_x86_64.whl (1.5 MB)
ERROR: Could not install packages due to an EnvironmentError: [Errno 28] No space left on device

WARNING: You are using pip version 20.3; however, version 21.0.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/home/container/main.py", line 3, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'
container@pterodactyl~ Server marked as offline...

**Comment by kittylegitcheck** [comment]
i have 1.5 gb of space

**Comment by Darkempire78** [comment]
1.5gb of available storage or 1.5 on the whole disk ?
