### ISSUE TITLE
Cant lock /unlock channels.

### ISSUE THREAD

**Issue by VerstreuteSeele** [Darkempire78/Raid-Protect-Discord-Bot#17]
Hey.

So when I try to lock a channel with #name or ID it always says channel not found. When I do just the name without "#" in front of it I get this: Command raised an exception: IndexError: list index out of range

Any ideas on how to fix that?

Having the same error when trying to allow spam in a particular channel :/

My bot has all perms (is admin as well)

**Comment by Darkempire78** [comment]
Can you send me a screenshot of the bug please (the command and the answere) ?
When you write the channel's name with the #, it is mentionned ?

**Comment by VerstreuteSeele** [comment]
sure. and yes it is mentioned. 
http://pays.host/uploads/5d0eccdc-55e1-488c-a47c-01bc92c9c04a/TeGA1dtn.png

**Comment by VerstreuteSeele** [comment]
Here is the one when I try to use allowspam

http://pays.host/uploads/5d0eccdc-55e1-488c-a47c-01bc92c9c04a/OB5yvnar.png

**Comment by Darkempire78** [comment]
Fixed!
