### ISSUE TITLE
some small issues 

### ISSUE THREAD

**Issue by felixsam359** [Darkempire78/Raid-Protect-Discord-Bot#19]
The bot is working very fine and really like it. But I encountered some small issues.
1/ Anyone in the server can use ```?userinfos``` command. 
2/ Anyone in the server can use ```?lock channel```. 
The above are not a big problem but still it would have been better if that command could only be used by a specific role.

The last one if someone failed the captcha bot will kick him and invite again in dms. The invite link created by the bot is permanent and never expires.It would have been little better if the bot generated expiring invite links.

 Taking an example suppose someone joined my server via a expiring invite link generated by me. He failed the captcha in first attempt. The bot send him the  permanent invite link in dm and kick him and he succeeds in second attempt. After staying in the server for sometime he turned malicious.He spammed like raiders. He got kicked by auto mod of your bot but he can join again by the inv link sent by the bot in your and spam again. And if bad luck all the mods are offline at that time can't ban him.I know this a very time taking and tiring process for the malicious people. But there are a people like that who want to spam like even after they get kicked.
 
The above scenario is 1 in 1000 but there is 0.001%chance.

**Comment by Darkempire78** [comment]
All was fixed!
Thank you
