### ISSUE TITLE
Is it possible to add a botinfo command to the bot?

### ISSUE THREAD

**Issue by P1rate6** [Darkempire78/Raid-Protect-Discord-Bot#2]
i tried adding the command myself and there was no luck

**Comment by Darkempire78** [comment]
That is to say ? What is the problem and what is your command ? Please join more information and why not screenshots 👍

**Comment by Darkempire78** [comment]
What do you want in the botinfo cammand ?  🤔

**Comment by P1rate6** [comment]
can you add me on discord, i will talk more about the issue i have

**Comment by Darkempire78** [comment]
Yes, add me : Darkempire#8245

**Comment by P1rate6** [comment]
i sent you a friend request a couple days ago

**Comment by Darkempire78** [comment]
What is your pseudo because I have a lot of requests :/

**Comment by P1rate6** [comment]
1564

**Comment by Darkempire78** [comment]
Problem fixed, just a problem of class name.
