### ISSUE TITLE
Multi-Server Support?

### ISSUE THREAD

**Issue by VerstreuteSeele** [Darkempire78/Raid-Protect-Discord-Bot#21]
Hey man. was just wondering if/when you will add multi-server support to this

**Comment by Darkempire78** [comment]
Indeed it can be an interesting improvement. To do this, we can either improve the current system or change to a database.

**Comment by VerstreuteSeele** [comment]
So are you going to add this? 
An update to the current system would be nice. 
and if you add a database I would use MongoDB as it doesnt need any software installation and is beginner-friendly

**Comment by Darkempire78** [comment]
@VerstreuteSeele I agree for MongoDB

**Comment by Darkempire78** [comment]
> So are you going to add this?
certainly in the future

**Comment by VerstreuteSeele** [comment]
near future? :)

**Comment by Darkempire78** [comment]
I hope 😂

**Comment by VerstreuteSeele** [comment]
Did it myself - closed

**Comment by Darkempire78** [comment]
@VerstreuteSeele 
It is possible for you to make a Pull request ?

**Comment by VerstreuteSeele** [comment]
u got the files. just... yeah enjoy and let me close this lol.
