### ISSUE TITLE
Adding commands for Manual Bans and Kicks.

### ISSUE THREAD

**Issue by XeroSaber0825** [Darkempire78/Raid-Protect-Discord-Bot#25]
Hi,

So I downloaded your bot on a whim, and added my own commands to it. Only problem is, when I use the commands in Discord it gives me an error. How would I fix it?
![Screenshot (8)](https://user-images.githubusercontent.com/81821060/114126124-a8e04900-98ac-11eb-9eeb-fc0b8bec989c.png)

**Comment by Darkempire78** [comment]
New moderation commands have been added!
