### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by Mikquaj** [Darkempire78/Raid-Protect-Discord-Bot#27]
![image](https://user-images.githubusercontent.com/81552040/114528005-e1837800-9c48-11eb-9d1d-9c02a91474da.png)
![image](https://user-images.githubusercontent.com/81552040/114528042-e9dbb300-9c48-11eb-990d-d67b4d7ce9fd.png)
python shows an import error in Cogs.onMessage but there is no such import

**Comment by Darkempire78** [comment]
Did you import modules from the requirements.txt file ?

**Comment by Darkempire78** [comment]
You have to download the version 1.0.6 of profanity_check from https://github.com/dimitrismistriotis/profanity-check with `git+https://github.com/dimitrismistriotis/profanity-check`.
So, uninstall your current version and download the 1.0.6.
