### ISSUE TITLE
         bot.load_extension(f"Cogs.{filename[:-3]}")

### ISSUE THREAD

**Issue by ShadowGaming100** [Darkempire78/Raid-Protect-Discord-Bot#28]
this part of the code has problems
![Screenshot_20210507-143118-582](https://user-images.githubusercontent.com/81495140/117450137-2301fd00-af41-11eb-9226-b5e0b460f97d.png)
#

**Comment by Darkempire78** [comment]
The issue's title is not related with the screenshot...

**Comment by Darkempire78** [comment]
Write `pip install -r requirements.txt` in your console

**Comment by ShadowGaming100** [comment]
> Write `pip install -r requirements.txt` in your console

where in main.py or what i am doing in replit

**Comment by Darkempire78** [comment]
In the console 
![image](https://user-images.githubusercontent.com/50015928/117471959-aaa73600-af58-11eb-8055-309197d10fd7.png)

**Comment by ShadowGaming100** [comment]
> In the console
> ![image](https://user-images.githubusercontent.com/50015928/117471959-aaa73600-af58-11eb-8055-309197d10fd7.png)

showing this
![Untitled](https://user-images.githubusercontent.com/81495140/117488919-3cb93980-af6d-11eb-9aea-c35d5e239720.png)
