### ISSUE TITLE
Help Command

### ISSUE THREAD

**Issue by FeelsBadMan1** [Darkempire78/Raid-Protect-Discord-Bot#31]
Hello again,
I just noticed after i updated the Botversion that the help command got a issure. I know what exactly the issure is but it would be nice if you could solve it. I also can solve it by my own but i think others  will face the same issure too. Embed descriptions have a characterlimit of 1024 characters and the embed you created is longer then that so withon throws a isssure into the discordchat. There are different ways to solve it. you could use the new buttonlibary to switch betweeen different embeds from the discord.py libary with components support created by a friend of mine or use discord.py menus what you manually clone from github to change embeds by reactions. However here is the issure i get:
![image](https://user-images.githubusercontent.com/40109798/121259465-71901780-c8b0-11eb-9316-f15d9381304f.png)

**Comment by Darkempire78** [comment]
What is Botversion ? In all case the help command work in the classic configuration

**Comment by FeelsBadMan1** [comment]
Its Botversion 1.7.2 and i just added a infocog. thats inside of the cog:
![image](https://user-images.githubusercontent.com/40109798/121394145-56291900-c951-11eb-8d30-f86ffecd68b8.png)

**Comment by FeelsBadMan1** [comment]
here this shows better what i mean:
![image](https://user-images.githubusercontent.com/40109798/121681265-e171ee00-caba-11eb-8ffa-4dcdaf83ae2d.png)

**Comment by FeelsBadMan1** [comment]
@Darkempire78 even after i removed the infocog so its on the sate you uploaded iton github i still get the error that the message is too long.

**Comment by Darkempire78** [comment]
No, I tried it and the help command works in the classic configuration

**Comment by FeelsBadMan1** [comment]
yea in the classic cofig (code what i downloaded and changed nothing) it print me the must be fewer then 1024 in length error.
