### ISSUE TITLE
Command raised an exception: AttributeError: 'int' object has no attribute 'lower'

### ISSUE THREAD

**Issue by Owned67** [Darkempire78/Raid-Protect-Discord-Bot#35]
Bonjour,

.giveroleaftercaptcha 962967290020790282

04/05/2022, 16:33:21
Command raised an exception: AttributeError: 'int' object has no attribute 'lower'

Le role est malgré tout assigné.
 ```
ROLE GIVEN AFTER CAPTCHA - (?giveroleaftercaptcha <role ID/off>)
Role given after captcha : @membre
```

Si on echec le captcha, je ne peux plus rejoindre le serveur, le délai reste figé à 3 (voir capture d'écran)

Une autre erreur:
Log failed (onJoin) : name 'elf' is not defined

des avertissements au démarrage:
D:\Python\Python36\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator TfidfTransformer from version 0.24.0 when using version 0.24.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
D:\Python\Python36\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator TfidfVectorizer from version 0.24.0 when using version 0.24.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
D:\Python\Python36\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator LinearSVC from version 0.24.0 when using version 0.24.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
D:\Python\Python36\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator _SigmoidCalibration from 
![Discord_sYkhuaYWmm](https://user-images.githubusercontent.com/1497809/166705708-a4c5b65a-4296-42ef-8cf1-aeb63d517102.png)
version 0.24.0 when using version 0.24.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
D:\Python\Python36\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator CalibratedClassifierCV from version 0.24.0 when using version 0.24.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)

**Comment by Darkempire78** [comment]
@Owned67 Thanks, I fixed it in the latest commit 85ff15ac3099180afcf7486d961c440868e8406f

**Comment by Owned67** [comment]
Si on echec le captcha, je ne peux plus rejoindre le serveur, le délai reste figé à 3 (voir capture d'écran)

Cela fait plus de 5 minutes que j'ai fail le captcha, je suis toujours bloqué :( 

Une autre erreur:
Log failed (onJoin) : name 'elf' is not defined

**Comment by Darkempire78** [comment]
haha, j'étais justement en train de regarder tous les issues sur mes projets github xD

Sinon, au niveau du timer ça semble simplement être un bug du coté de GitHub (à vérifier), peut être qu'en changeant de serveur ou de salon ça règle le problème (voir relancer discord)

**Comment by Darkempire78** [comment]
Je viens de fixer la petite erreur de frappe dans onJoin 85ff15ac3099180afcf7486d961c440868e8406f

**Comment by Owned67** [comment]
> 

relancer discord semble fonctionner merci.

concernant les warnings, je peux les ignorer ?
