### ISSUE TITLE
allowspam problem

### ISSUE THREAD

**Issue by Owned67** [Darkempire78/Raid-Protect-Discord-Bot#36]
`?allowspam #😏meme`

Command raised an exception: KeyError: 'INVALID_CHANNEL_ENABLE'

Pourtant en faisant ?settings, tout semble être bon:
Channel where spam is allowed : 😏meme, 😏memes

edit: j'ai testé le mode nudité, téléchargé une image de gens nu puis uploadé sur le discord, le module est activé mais aucune sanction (pas de suppression etc..). Je n'ai aucun droits d'admin/modo etc...

**Comment by Darkempire78** [comment]
fixé c1b5bb016479daadd6ed83620d21221380ec40e0

**Comment by Darkempire78** [comment]
Le mode anti nudité n'a pas 100% de précision mais marche pas mal normalement

**Comment by Owned67** [comment]
> 

bah j'ai testé plusieurs images et rien n'a été fait donc je doute sur le faite qu'il fonctionne ^^
