### ISSUE TITLE
role untested cree en boucle

### ISSUE THREAD

**Issue by Owned67** [Darkempire78/Raid-Protect-Discord-Bot#37]
Bonjour,

j'ai le role untested 5-6 fois dans mes rôles ayant exécuté le fichier plusieurs fois... 

je pensais à un oubli de vérification (si le role existe, on fait rien) dans un fichier .py ou c'est volontaire ?

**Comment by Darkempire78** [comment]
Le bot crée le role a chaque fois que tu fais la commande ?setup
Il n'y a pas de vérification pour savoir si le role existe déjà pour ne pas supprimer un role qui ne devrait pas l'être (en théorie tu ne fais la commande qu'une seule fois xD)
Après c'est possiblement améliorable je pense

**Comment by Owned67** [comment]
en théorie oui mais bon j'aime bien tout tester pour voir les éventuels bug :)

**Comment by Darkempire78** [comment]
Pas de soucis, ils seront tous fixés 👀
