### ISSUE TITLE
load_extension is now a coroutine

### ISSUE THREAD

**Issue by GameCreep035** [Darkempire78/Raid-Protect-Discord-Bot#39]
Hey ! When we load cogs in main.py, we just do bot.load_extension, but now, load_extension is a coroutine, so we can't put it in if __name__ == '__main__': .
The program now can't run, beceause you need to await the load ext but if  name == main isn't a function.
![unknown](https://user-images.githubusercontent.com/103676650/167310970-4c30e410-a75e-41c6-b669-25761635bfbd.png)
![unknown1](https://user-images.githubusercontent.com/103676650/167310984-2eb964d3-29fc-47ab-8f1c-491312104ada.png)

**Comment by Darkempire78** [comment]
The v2.0.0a is a not an stable released, the current version is 1.7.3
