### ISSUE TITLE
Bot randomly kicking users

### ISSUE THREAD

**Issue by FeelsBadMan1** [Darkempire78/Raid-Protect-Discord-Bot#4]
Hello, i did setup the bot correctly but if someone join and a system welcomemessage appears in the welcome channel then the bot is sending a message in the logchannel that the joined user spammed in welcome channel. i removed the welcome channel and wrote "?verify" in the verifychannel then the user got kicked too. it was just one message and im not sure how to solve this issure.
Another issure is, that the bot dont dm new users with the verification captha and i not see any command that manuelly sending the captha to the user.
![Opera Momentaufnahme_2020-11-13_094656_discord com](https://user-images.githubusercontent.com/40109798/99048747-3df94300-2596-11eb-8821-9f37d042b5f3.png)

**Comment by Darkempire78** [comment]
I will check that today

**Comment by Darkempire78** [comment]
Use the latest version of the bot, it's corrected. Thanks for you report !
