### ISSUE TITLE
Probleme install

### ISSUE THREAD

**Issue by K776** [Darkempire78/Raid-Protect-Discord-Bot#6]
Salut j'ai c'est 2 pb
![image](https://user-images.githubusercontent.com/67116297/100476925-2e761000-30e7-11eb-9009-ea390fca0bf1.png)

![image](https://user-images.githubusercontent.com/67116297/100476912-23bb7b00-30e7-11eb-92a0-55298b41501e.png)

**Comment by K776** [comment]
J'ai vue que le requierement avais changez et j'ai sa mnt 
![image](https://user-images.githubusercontent.com/67116297/100482064-86684300-30f6-11eb-85d0-f1b4257d1d1a.png)

**Comment by Darkempire78** [comment]
Attention, tu devrais installer les modules du programme sans toucher aux libraires python du système.
Je te recommande d'utiliser un environnement, ça réglera certainement le problème.
