### ISSUE TITLE
Bot do random stuff

### ISSUE THREAD

**Issue by FeelsBadMan1** [Darkempire78/Raid-Protect-Discord-Bot#7]
Hello, the bot is almost working correctly but the bot did setup some permssions so users not could send messages in the verification channel and they not could see the instruction channel how to verify so i changed the permissions back to the settings that let new users see these channels but after some time the bot changing it back and its annoying to change channelpermissions many times because of the bot.

**Comment by Darkempire78** [comment]
Yes, the bot adds permissions automatically to each channel when you setup the captcha. 
I will add a command to ignore specific channels from permissions.

**Comment by Darkempire78** [comment]
I change the script to solve this error. Use the new version!
